### PR TITLE
Added bookmark cookies for prompt.

### PR DESCRIPTION
**Pull request by fetzerms**
This patch addes two cookies for the prompt:

```
\b - Will display the bookmark, which corresponds to the current remote site.
\B - If a bookmark is found, it acts like \b. Otherwise like \h.
```

This allows to have a prompt like:

`[lftp] user@Bookmark ~>`

### CODE REVIEW

**Comment by fetzerms** [comment]
I changed it, so it uses the WITH_PASSWORD constant. Actually this only implements half my goal.
My goal was to have some sort of "sitename" variable. Which gets displayed regardless of the current path on the remote site. But i think the current bookmark scheme does not qualify to be used for this, as the bookmarks are not limited to specific sites.

`user@site:/pub `

and

`user@site:/incoming`

Can be two different bookmarks, but on the same site. Maybe some sitename mapping from user@host to sitename has to be implemented. Probably as an extra cookie. What do you suggest/think?

**Comment by lavv17** [comment]
Consider remembering last used bookmark in a member of CmdExec.

**Comment by fetzerms** [comment]
I think i will consider this. A ip:port to site-alias mapping might still be handy.

**Comment by lavv17** [comment]
You can lookup a bookmark without a path, or a bookmark with longest prefix match.

**Comment by fetzerms** [comment]
I was rather thinking about a completely new keyvalue store for saving aliases-to-IP pairs. This might be, what I was actually looking for. Maybe some "Host-Alias". Like a traditional Linux hosts file. This map could also be used to look up names when resolving hosts.

What do you think? Should I give this a try?

**Comment by lavv17** [comment]
This can be done via the setting system, something like dns:host/example.com
123.234.45.56

вт, 18 окт. 2016, 12:08 Matthias Fetzer <notifications@github.com>:

**Comment by lavv17** [comment]
Please try d45f20b30e7182b56b634e06d4895dba49024d75 (dns:name setting).
Also consider ~/.hostaliases file.

**Comment by fetzerms** [comment]
I will test it this weekend. Sorry, I did not have much time to work on this issue, last week. 
But it looks like this is what I needed.

**Comment by lavv17** [comment]
Issue seems to be resolved by introducing dns:name setting.

**Pull request closed without merging**
