### PR TITLE
Fixes issue #474

### LINKED ISSUE #474: segmentation fault mirroring http server folder with many files
lftp version: 4.8.3

I'm getting 
```
“lftp” terminated by signal SIGSEGV (Address boundary error)
```
When doing:
```
#!/usr/bin/lftp -f
lcd localdir
open http://domain.com/remotedir/
mirror --verbose=3 -c --delete-first  --parallel=4 exampledir
```
The remote dir is in a http server, using h5ai for listing. For other folders in the same server with less files it works, but for a folder with many files, it gives the aforementioned error while "Getting directory contents".

### PR DESCRIPTION
**Pull request by gilcu3**
Fixes issues with big http dirs

### CODE REVIEW

**Comment by gilcu3** [comment]
I have some doubt on how to implement function remove_tags with the provided xstring class. It's possible to do it, but as there is no method in xstring to modify a single character, I would be forced to use set_substr, which is not the most efficient for that case. Do you have any thoughts about this @lavv17 ??

**Comment by gilcu3** [comment]
Requested changes done, saw function shell_encode above and got answer to my question.

**Comment by gilcu3** [comment]
@lavv17 are you ok with implemented changes?

**Comment by lavv17** [comment]
Thanks!

**Pull request merged**
