### PR TITLE
SSH_Access: be more liberal about recognizing password prompts

### PR DESCRIPTION
**Pull request by peti**
A SUSE customer reported an issue where the use of a 3rd party
PAM module in stack changed the password prompt to:

    UNIXADS password for username:

Unfortunately, the ssh parsing code in lftp does not recognize
this as a password prompt, which means that the login process
gets stuck.

We have found that accepting all strings that contain the phrase
"password" and end in a colon works very well and it also covers
this particular case.

### CODE REVIEW

**Comment by lavv17** [comment]
You have to leave this, as it does not end with a colon:
ends_with(b,b+s,"'s password")

**Comment by peti** [comment]
> You have to leave this, as it does not end with a colon:
>  `ends_with(b,b+s,"'s password")`

Good catch. I have reinstated that case and force-pushed a new version.

**Comment by lavv17** [comment]
Please note that the string b is not null-terminated, pass "s" or "b+s" to "contains" function.

**Comment by peti** [comment]
It's not that simple, unfortunately. `strcasestr()` expects two `\0`-terminated strings and a corresponding `strncasestr()` function doesn't seem to exist. There is `std::find()`, of course, but that won't ignore case. Duh. I'll need to think about a proper solution for this.

**Comment by lavv17** [comment]
Maybe regex will do.

**Comment by peti** [comment]
I'm looking at `std::search()` with a case-less comparison predicate right now ... it might be too new, i.e. it seems to be only in C++20. Regex matching could be a good fallback, though, you are right.

**Comment by peti** [comment]
OK. I pushed a new version that doesn't assume a NUL-terminated buffer any more.

**Pull request merged**
