### PR TITLE
WIP: Adding docker file

### LINKED ISSUE #359: Create automated docker image build
It will be very nice to have an oficial docker image of lftp.

### PR DESCRIPTION
**Pull request by pgbezerra**
Alpine image.

Closes #359

### CODE REVIEW

**Comment by paulobezerr** [comment]
@lavv17, I am having problems with gnulib-tool in alpine linux.
If takes too long I'll change to debian's image, ok?

**Comment by lavv17** [comment]
That's ok. Is the file required to be in the top directory?
BTW, I'd better avoid specifying a hard-coded versions, it's likely to break when time goes on.

**Comment by paulobezerr** [comment]
No, it is not mandatory.
Just the command to build an image will change. Ex:

Lets suppose this path: `docker_build/DockerFile`, the command to build will be:

```bash
docker build -t lavv17/lftp docker_build
```

Which directory do you prefer?

**Comment by kevzettler** [comment]
Whats the status on this? I was about to build a Dockerfile for this myself because I cannot get it to compile natively on OSX

**Comment by paulobezerr** [comment]
Actually I am with personal problems and I didn't finish this yet. I appreciate if you create your docker file and sent here. :)

**Comment by lee-reinhardt** [comment]
Here's an alpine `Dockerfile` to build lftp that I needed for a recent project. Figured I'd share here. There may be a few unnecessary things being installed, but this is the working version I am using.

```
FROM alpine AS build_lftp

RUN apk add --no-cache git coreutils

WORKDIR /lftp

RUN git clone https://github.com/lavv17/lftp /lftp
RUN git checkout mod
RUN git submodule add https://git.savannah.gnu.org/git/gnulib.git

ENV PATH="/lftp/gnulib:${PATH}"

RUN apk add --no-cache gcc \
  make \
  g++ \
  bison \
  gnutls \
  gnutls-dev \
  gperf \
  zlib-dev \
  autoconf \
  libtool \
  gettext \
  gettext-dev \
  automake \
  zlib-dev \
  readline-dev \
  ncurses-dev \
  gcompat

RUN ./bootstrap --gnulib-srcdir=/lftp/gnulib
RUN ./autogen.sh
RUN make
RUN make install

RUN /usr/local/bin/lftp --version
```

**Pull request closed without merging**
